#spring:
#  mvc:
#    static-path-pattern: /res/**
#  web:
#    resources:
#      static-locations: classpath:/haha/

spring:
  web:
    resources:
#      当配置为false时所有静态资源都无法访问
      add-mappings: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
